<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/ThreatService/WSDL/Client/ThreatService/SampleSubmission.xsd" xmlns:tns="http://xmlns.example.com/1442299909581" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1442299909581">
    <import namespace="http://www.tibco.com/schemas/ThreatService/WSDL/Client/ThreatService/SampleSubmission.xsd" location="../../../XSD/Neuron/SampleSubmission.xsd"/>
    <message name="G2NeuronSampleSubmissionRq">
        <part name="Input" element="ns:SampleSubmissionRq"/>
    </message>
    <message name="G2NeuronSampleSubmissionRs">
        <part name="Output" element="ns:SamplesubmissionRs"/>
    </message>
    <portType name="PortType">
        <operation name="G2NeuronSampleSubmission">
            <input message="tns:G2NeuronSampleSubmissionRq"/>
            <output message="tns:G2NeuronSampleSubmissionRs"/>
        </operation>
    </portType>
</definitions>