<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.tibco.com/schemas/GCCPortal_For_G2_V1.0/WSDL/Client/G2XSD/Routing/RoutingCheckingRq.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.trendmicro.com/ESB/ACS/schemas/SRFDispatch" xmlns:ns3="http://www.tibco.com/schemas/GCCPortal_For_G2_V1.0/WSDL/Client/G2XSD/Routing/Schema.xsd2" xmlns:tns="http://xmlns.example.com/1417784306059" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1417784306059">
    <import namespace="http://www.trendmicro.com/ESB/ACS/schemas/SRFDispatch" location="../../XSD/Neuron/SRFDispatch.xsd"/>
    <import namespace="http://www.tibco.com/schemas/GCCPortal_For_G2_V1.0/WSDL/Client/G2XSD/Routing/RoutingCheckingRq.xsd" location="G2XSD/Routing/RoutingCheckingRq.xsd"/>
    <import namespace="http://www.tibco.com/schemas/GCCPortal_For_G2_V1.0/WSDL/Client/G2XSD/Routing/Schema.xsd2" location="G2XSD/Routing/RoutingCheckingRs.xsd"/>
    <message name="RoutingCheckRq">
        <part name="part1" element="ns2:G2_RoutingCheckRq"/>
    </message>
    <message name="RoutingCheckRs">
        <part name="part1" element="ns3:RoutingCheckingRs"/>
    </message>
    <portType name="PortType">
        <operation name="RoutingCheck">
            <input message="tns:RoutingCheckRq"/>
            <output message="tns:RoutingCheckRs"/>
        </operation>
    </portType>
</definitions>