<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.tibco.com/schemas/PLSService/WSDL/Client/DTSResponse" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/PLSService/WSDL/Client/DTSRequest" xmlns:tns="http://xmlns.example.com/1348556108347" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1348556108347">
    <import namespace="http://www.tibco.com/schemas/PLSService/WSDL/Client/DTSResponse" location="UpdatePOStatusResponse.xsd"/>
    <import namespace="http://www.tibco.com/schemas/PLSService/WSDL/Client/DTSRequest" location="UpdatePOStatusRequest.xsd"/>
    <message name="DTSRq">
        <part name="Input" element="ns:UpdatePOStatusRequest"/>
    </message>
    <message name="DTSRs">
        <part name="Output" element="ns2:UpdatePOStatusResponse"/>
    </message>
    <portType name="IStreamOneUpdatePOStatusService">
        <operation name="UpdatePOStatus">
            <input message="tns:DTSRq"/>
            <output message="tns:DTSRs"/>
        </operation>
    </portType>
</definitions>