<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/GCCPortal_For_G2_V1.0/WSDL/Client/AMSS Solution Provided XSD/Schema.xsd" xmlns:tns="http://xmlns.example.com/1427950994770" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1427950994770">
    <import namespace="http://www.tibco.com/schemas/GCCPortal_For_G2_V1.0/WSDL/Client/AMSS Solution Provided XSD/Schema.xsd" location="GetSRInfoByClosecallback.xsd"/>
    <message name="GetSRInfoByClosecallbackRq">
        <part name="part1" element="ns:GetSRInfoByClosecallbackRq"/>
    </message>
    <message name="GetSRInfoByClosecallbackRs">
        <part name="part1" element="ns:GetSRInfoByClosecallbackRs"/>
    </message>
    <portType name="PortType">
        <operation name="GetSRInfoByClosecallback">
            <input message="tns:GetSRInfoByClosecallbackRq"/>
            <output message="tns:GetSRInfoByClosecallbackRs"/>
        </operation>
    </portType>
</definitions>